### ISSUE TITLE
Error when setting allowance

### ISSUE THREAD

**Issue by Miojo** [sontungpytn/axie-bot#1]
Approve value  1
(node:4056) UnhandledPromiseRejectionWarning: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":49,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (0)\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x3b9aca00\",\"type\":\"0x0\",\"from\":\"0

I think the error is **gas required exceeds allowance (0)** but I don't know how to fix

**Comment by kickboxer** [comment]
@Miojo How did you fix it?
